# Cấu hình server
server:
  port: 8080
  servlet:
    context-path: /v1

# Cấu hình Spring Boot
spring:
  application:
    name: dna-testing-system
  
  # Cấu hình MySQL cho XAMPP
  datasource:
    url: jdbc:mysql://localhost:3306/dna_testing_system
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # Cấu hình JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

# Logging để debug
logging:
  level:
    web: DEBUG
    org.springframework.web: DEBUG