server:
  port: 8080
  servlet:
    context-path: /v1

spring:
  application:
    name: dev
  thymeleaf:
    cache: false
  datasource:
    url: "jdbc:mysql://localhost:3306/dna_testing_system"
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true