server:
  port: 8080

spring:
  application:
    name: dev
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://mysql:3306/dna_booking_db
    username: ThuyTien
    password: 38632347tT@
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
