
  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/dna_booking_db
      username: ThuyTien
      password: 38632347tT@
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          connection:
            zeroDateTimeBehavior: convertToNull
    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
    mail:
      host: smtp.gmail.com
      port: 587
      username: your-email@gmail.com
      password: your-app-specific-password
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
  server:
    port: 8080
